apiVersion: v1
kind: Service
metadata:
  name: faithful-e2e-g
  namespace: colossus-faithful-e2e-g
  labels:
    app: faithful-e2e-g
    managed-by: colossus
spec:
  type: ClusterIP
  selector:
    app: faithful-e2e-g
  ports:
    - port: 80
      targetPort: 80
